confirm_os_window_close 0

font_family      FiraCodeNF-Reg
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 9

force_ltr yes

# symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

font_features FiraCode-Regular +zero +onum
# modify_font underline_position -2
# modify_font underline_thickness 150%
# modify_font strikethrough_position 2px
# cursor #ffffff
# cursor_text_color #000000

cursor_shape underline
cursor_underline_thickness 2
cursor_beam_thickness 2
cursor_blink_interval 0.5
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
# cursor_trail_color none

scrollback_lines 1000
# url_color #0087bd
url_style curly
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes

window_padding_width 15


# BEGIN_KITTY_THEME
# Hardcore
include current-theme.conf
# END_KITTY_THEME
